name: Dev

on:
  push:
    branches:
      - dev
    paths:
      - main.py
      - requirements.txt
      - deploy.txt
      - deploy_dev.txt

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
    secrets: inherit
