name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v0.7.1
        with:
          credentials_json: ${{ secrets.GCP_KEYFILE }}

      - name: Deploy points
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: points
          runtime: python39
          memory_mb: 512
          entry_point: handler
          region: us-east4
          env_vars: "BUCKET_NAME=${{ secrets.BUCKET_NAME }}"
