name: Deploy Dev

on:
  push:
    branches:
      - dev
    paths:
      - main.py
      - requirements.txt
      - .github/workflows/deploy.yml
      - .github/workflows/deploy_dev.yml

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
    secrets: inherit
