name: Main

on:
  push:
    branches:
      - main
    paths:
      - main.py
      - requirements.txt
      - deploy.txt
      - deploy_main.txt

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: main
    secrets: inherit
