name: Deploy Main

on:
  push:
    branches:
      - main
    paths:
      - main.py
      - requirements.txt
      - .github/workflows/deploy.yml
      - .github/workflows/deploy_main.yml

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: main
    secrets: inherit
