name: Dev
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
    secrets: inherit
  train:
    uses: ./.github/workflows/train.yml
    with:
      environment: dev
    secrets: inherit
