name: Dev
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
    secrets: inherit

  train:
    uses: ./.github/workflows/train.yml
    with:
      environment: dev
      n_trials: 100
      timeout: null
      max_players_per_club: 5
      dropout: 0.0
      n_times: 1
    secrets: inherit
