name: Experiment

on:
  workflow_dispatch:
    inputs:
      n_trials:
        description: Number of trials
        required: true
        default: '250'
      max_players_per_club:
        description: Max players per club
        required: true
        default: 5
      dropout:
        description: Dropout
        required: true
        default: 0.1
      dropout_type:
        description: Dropout Type
        required: true
        default: club
      n_times:
        description: Number of drafts
        default: 50
      k:
        description: NDCG K
        required: true
        default: 20

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment: ${{ github.REF_NAME }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_KEYFILE }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install requirements
        run: pip install -r requirements-train.txt

      - name: Train
        run: |
          python train.py \
          --n-trials ${{ inputs.n_trials }} \
          --max-players-per-club ${{ inputs.max_players_per_club }} \
          --dropout ${{ inputs.dropout }} \
          --dropout-type ${{ inputs.dropout_type }} \
          --n-times ${{ inputs.n_times }} \
          --k ${{ inputs.k }} \
          -t 'experiment.yml'
        env:
          DRAFT_URL: ${{ secrets.DRAFT_URL }}
          DRAFT_KEY: ${{ secrets.DRAFT_KEY }}
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
