name: Train Model

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      n_trials:
        required: false
        type: int
      timeout:
        required: false
        type: string
      max_players_per_club:
        required: false
        type: string
      dropout:
        required: false
        type: string
      n_times:
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_KEYFILE }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install requirements
        run: pip install -r requirements-train.txt

      - name: Retrain
        run: |
          python train.py --n-trials {{ inputs.n_trials }}
        env:
          DRAFT_URL: ${{ secrets.DRAFT_URL }}
          DRAFT_KEY: ${{ secrets.DRAFT_KEY }}

      - name: Upload artifact
        run: gcloud storage cp model.txt gs://${{ secrets.BUCKET_NAME }}/points/model.txt
