name: Train

on:
  push:
    branches:
      - main
      - dev
    paths:
      - train.py
      - query.sql
      - requirements-train.txt
      - .github/workflows/train.yml

  schedule:
    - cron:  '0 0 * * *'

jobs:
  train:
    runs-on: ubuntu-latest
    environment: ${{ github.REF_NAME }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_KEYFILE }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install requirements
        run: pip install -r requirements-train.txt

      - name: Train
        run: |
          python train.py \
          --n-trials 1000 \
          --max-players-per-club 5 \
          --dropout 0.1 \
          --n-times 50 \
          --k 20
          -t 'train.yml'
        env:
          DRAFT_URL: ${{ secrets.DRAFT_URL }}
          DRAFT_KEY: ${{ secrets.DRAFT_KEY }}
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

      - name: Upload artifact
        run: gcloud storage cp model.txt gs://${{ secrets.BUCKET_NAME }}/points/model.txt
